// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AcceptInviteResponse = { workspaceId: string, 
/**
 * Already a member before this invite; the role stayed as it was.
 */
alreadyMember: boolean, };
