// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One account, as the admin pages list it.
 */
export type AdminUser = { id: string, email: string, name: string | null, emailVerified: boolean, twoFactor: boolean, disabled: boolean, 
/**
 * Listed in `KESTREL_ADMIN_EMAILS`.
 */
admin: boolean, 
/**
 * The signed-in admin looking at the list.
 */
you: boolean, createdAtMs: number, 
/**
 * The latest use of a session still on record; `null` once they've all expired.
 */
lastSeenAtMs: number | null, workspaces: number, liveSessions: number, };
