// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdminUser } from "./AdminUser";

/**
 * `GET /api/admin/overview`.
 */
export type AdminOverview = { users: number, verifiedUsers: number, twoFactorUsers: number, disabledUsers: number, signupsLast7d: number, workspaces: number, 
/**
 * Workspaces with more than one member.
 */
sharedWorkspaces: number, 
/**
 * Signed-in sessions that haven't expired.
 */
liveSessions: number, 
/**
 * Tests running on this engine now.
 */
runningTests: number, 
/**
 * The newest accounts, newest first.
 */
recentSignups: Array<AdminUser>, };
