// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdminMail } from "./AdminMail";
import type { CapsInfo } from "./CapsInfo";

/**
 * `GET /api/admin/settings`: how this engine is configured. Read-only (it's all environment
 * variables), and without secrets: no token, database URL or SMTP credentials.
 */
export type AdminSettings = { version: string, signupOpen: boolean, adminEmails: Array<string>, publicUrl: string | null, 
/**
 * `None` when email is off.
 */
mail: AdminMail | null, 
/**
 * The address and port the engine listens on.
 */
listen: string, 
/**
 * Extra `Host` values accepted besides localhost.
 */
allowedHosts: Array<string>, trustedProxy: boolean, dbMaxConnections: number, caps: CapsInfo, };
