// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One workspace, as the admin pages list it.
 */
export type AdminWorkspace = { id: string, 
/**
 * Its name, or "<admin>'s workspace" for one that was never named.
 */
name: string, adminEmails: Array<string>, members: number, createdAtMs: number, 
/**
 * What its data takes up in the database.
 */
sizeBytes: number, };
