// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdminMail = { host: string, port: number, 
/**
 * `tls`, `starttls` or `none`.
 */
tls: string, from: string, 
/**
 * Whether it signs in to the SMTP server (the credentials themselves aren't shown).
 */
authenticated: boolean, };
