// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Confidence } from "./Confidence";
import type { Model } from "./Model";
import type { ModelFit } from "./ModelFit";

export type Analysis = { 
/**
 * Best first.
 */
fits: Array<ModelFit>, 
/**
 * None when inconclusive.
 */
best: Model | null, verdict: string, confidence: Confidence, 
/**
 * Slope of log(t − a) vs log n over the upper half of the range: ≈0 constant, ≈1 linear, ≈2
 * quadratic. A second opinion that doesn't depend on the candidate list.
 */
slope: number | null, 
/**
 * A runner-up that fits nearly as well.
 */
alsoPlausible: Model | null, explanation: string, };
