// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AuthRequest = { email: string, password: string, 
/**
 * This browser's existing workspace (from `localStorage`). On a first sign-in it becomes the
 * account's workspace if nobody owns it yet, so the data made before signing up isn't lost.
 */
workspace?: string, };
