// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Body = { "type": "none" } | { "type": "json", content: string, } | { "type": "raw", contentType: string, content: string, };
