// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BreakpointMode = { startRate: number, 
/**
 * How much each step raises the rate, in percent (at least +1 req/s).
 */
stepPercent: number, 
/**
 * How long each step lasts.
 */
stepMs: number, 
/**
 * The last step runs at this rate.
 */
maxRate: number, 
/**
 * A step breaks when more than this share of its requests fail (drops at the in-flight cap
 * count as failures).
 */
maxErrorPct: number, 
/**
 * A step also breaks when its p99 is above this.
 */
maxP99Ms: number | null, };
