// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BreakpointStep } from "./BreakpointStep";

export type BreakpointResult = { steps: Array<BreakpointStep>, 
/**
 * The highest rate whose step passed.
 */
heldRate: number | null, 
/**
 * The rate of the first step that failed. None if none did.
 */
brokeAtRate: number | null, };
