// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One step of a breakpoint run.
 */
export type BreakpointStep = { 
/**
 * Scheduled rate.
 */
rate: number, 
/**
 * What the target actually answered, per second.
 */
achievedRps: number, requests: number, 
/**
 * Failed requests plus drops, as a percentage of everything scheduled.
 */
errorPct: number, dropped: number, p50Ms: number, p99Ms: number, passed: boolean, 
/**
 * Why it failed, e.g. "p99 812 ms > 500 ms".
 */
reason: string | null, };
