// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Aggregated results for one 250 ms window.
 */
export type Bucket = {
  /**
   * Window end, in ms since the run started.
   */
  tMs: number;
  requests: number;
  errors: number;
  rps: number;
  p50Ms: number;
  p99Ms: number;
  /**
   * Open model: scheduled sends skipped because the in-flight cap was reached.
   */
  dropped: number;
  /**
   * Requests in flight at the end of the window.
   */
  inFlight: number;
  /**
   * Worst lateness of the scheduler in this window (open model). High values mean the load
   * generator, not the target, is the bottleneck.
   */
  lagMs: number;
};
