// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The caps as the UI shows them (`GET /api/health`), in the units its forms use.
 */
export type CapsInfo = { maxRps: number, maxInFlight: number, maxDurationS: number, maxTimeoutMs: number, maxSamples: number, maxWarmup: number, maxSweepS: number, maxN: number, maxPoints: number, };
