// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Endpoint } from "./Endpoint";

/**
 * A named set of endpoints, usually one API (one imported spec).
 */
export type Collection = { id: string, name: string, 
/**
 * Defaults for `{{…}}` in this collection's endpoints, e.g. `base`. The active environment's
 * variables and secrets override these.
 */
vars: { [key in string]: string }, endpoints: Array<Endpoint>, };
