// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Latency at one size. Medians use successful requests only.
 */
export type ComplexityPoint = { n: number, medianMs: number, p25Ms: number, p75Ms: number, samples: number, errors: number, 
/**
 * Median request body size at this n, to see how much growth is just transfer.
 */
requestBytes: number, responseBytes: number, 
/**
 * Median latency of the same bodies sent to the baseline (echo) endpoint, when there is one.
 */
baselineMedianMs: number | null, };
