// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ComplexityConfig = { 
/**
 * The endpoint must use a size generator (`{{n}}`, `{{n:int_array}}`, …) somewhere.
 */
endpointId: string, environment: string | null, minN: number, maxN: number, 
/**
 * How many sizes, spaced geometrically from `min_n` to `max_n`.
 */
points: number, 
/**
 * Samples per size; each is one shuffled round over all sizes.
 */
samples: number, 
/**
 * Requests at the middle size before measuring.
 */
warmup: number, timeoutMs: number, keepAlive: boolean, okStatuses: Array<number>, 
/**
 * Once a size's median exceeds this, larger sizes are dropped.
 */
slowMs: number, 
/**
 * Total time for the sweep.
 */
budgetMs: number, 
/**
 * Payload baseline (HANDOFF → Big-O, step 5): an echo endpoint on the same host. Each sample's
 * exact body is also sent there, so the report can show how much of the growth is transfer
 * and parsing rather than the endpoint's own work.
 */
baselineEndpointId: string | null, 
/**
 * Server state (HANDOFF → Big-O server-state sweeps): a request sent before each size's samples,
 * rendered with that size, e.g. `POST /seed?count={{n}}`, so "seed n rows, then time the query"
 * can be measured. With one set, sizes are swept one at a time instead of in shuffled rounds.
 */
setupEndpointId: string | null, 
/**
 * Sent after each size's samples (with the same n), e.g. to delete what setup made.
 */
teardownEndpointId: string | null, };
