// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ComplexityConfig = { 
/**
 * The endpoint must use a size generator (`{{n}}`, `{{n:int_array}}`, …) somewhere.
 */
endpointId: string, environment: string | null, minN: number, maxN: number, 
/**
 * How many sizes, spaced geometrically from `min_n` to `max_n`.
 */
points: number, 
/**
 * Samples per size; each is one shuffled round over all sizes.
 */
samples: number, 
/**
 * Requests at the middle size before measuring.
 */
warmup: number, timeoutMs: number, keepAlive: boolean, okStatuses: Array<number>, 
/**
 * Once a size's median exceeds this, larger sizes are dropped.
 */
slowMs: number, 
/**
 * Total time for the sweep.
 */
budgetMs: number, 
/**
 * Payload baseline (HANDOFF → Big-O, step 5): an echo endpoint on the same host. Each sample's
 * exact body is also sent there, so the report can show how much of the growth is transfer
 * and parsing rather than the endpoint's own work.
 */
baselineEndpointId: string | null, };
