// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Analysis } from "./Analysis";
import type { ComplexityPoint } from "./ComplexityPoint";
import type { PayloadResult } from "./PayloadResult";

export type ComplexityResult = { points: Array<ComplexityPoint>, analysis: Analysis, 
/**
 * Payload scaling runs only: the points read as bytes.
 */
payload: PayloadResult | null, };
