// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ComplexityPoint } from "./ComplexityPoint";

export type ComplexityProgress = { round: number, rounds: number, points: Array<ComplexityPoint>, };
