// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConcurrencyRound } from "./ConcurrencyRound";
import type { Finding } from "./Finding";

/**
 * Concurrency runs: what happened in each round, and what that suggests.
 */
export type ConcurrencyResult = { rounds: Array<ConcurrencyRound>, 
/**
 * Plain-language reading of the rounds, worst first.
 */
findings: Array<Finding>, };
