// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ConcurrencyConfig = { endpointId: string, environment: string | null, 
/**
 * Identical requests released together in each round.
 */
requests: number, 
/**
 * Bursts to fire. The request is rendered once per round, so `{{uuid}}` or `{{seq}}` differ
 * between rounds but not within one: each round is a fresh attempt at the same race.
 */
rounds: number, 
/**
 * Wait between rounds.
 */
pauseMs: number, timeoutMs: number, };
