// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StatusCount } from "./StatusCount";

export type ConcurrencyRound = { 
/**
 * 1-based.
 */
round: number, statuses: Array<StatusCount>, 
/**
 * Requests that got no response: timeouts, connection errors.
 */
failed: number, 
/**
 * 2xx responses.
 */
succeeded: number, 
/**
 * Different bodies among the 2xx responses. Several usually means several records were made.
 */
distinctBodies: number, 
/**
 * How long every request was in flight at once (from the last send to the first response).
 * 0 means some finished before others were sent, so they didn't all race.
 */
overlapMs: number, 
/**
 * From the first response to the last.
 */
spreadMs: number, };
