// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Tallies contract checks across a run.
 */
export type ContractSummary = {
  checked: number;
  undeclaredStatus: number;
  schemaMismatch: number;
  /**
   * Up to 5 distinct violation messages, redacted.
   */
  examples: Array<string>;
  /**
   * Under load only a sample of responses is validated.
   */
  sampled: boolean;
};
