// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ViolationKind } from "./ViolationKind";

/**
 * The outcome of checking one response.
 */
export type ContractCheck = { passed: boolean; kind: ViolationKind | null; message: string };
