// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `POST /api/import/curl`: one command, to fill in a request.
 */
export type CurlParseRequest = { command: string, };
