// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Endpoint } from "./Endpoint";

export type CurlParseResult = { 
/**
 * The URL is as written (not `{{base}}`-relative); the UI decides how it fits the collection.
 */
endpoint: Endpoint, 
/**
 * Options that were skipped or guessed, for the user to review.
 */
warnings: Array<string>, };
