// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ErrorCounts = { transport: number, timeout: number, http: number, rateLimited: number, clientResource: number, invalidRequest: number, };
