// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Why a request counted as an error (HANDOFF → Test catalogue → Error classification).
 */
export type ErrorClass = "transport" | "timeout" | "http" | "rateLimited" | "clientResource" | "invalidRequest";
