// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ExpectedResponse = { 
/**
 * `"200"`, a range like `"2XX"`, or `"default"`.
 */
status: string, 
/**
 * JSON Schema (2020-12) for a JSON body. `$ref`s point into the collection's `schema_defs`.
 */
schema: unknown, };
