// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExtractSource } from "./ExtractSource";
import type { ExtractTarget } from "./ExtractTarget";

/**
 * "After response" rule: copy one value from the response into the active environment.
 */
export type Extract = { source: ExtractSource, 
/**
 * Body: a path like `data.token` or `items[0].id` (empty = the whole body). Header: its name.
 */
path: string, target: ExtractTarget, 
/**
 * Variable or secret name, used as `{{name}}`.
 */
name: string, enabled: boolean, };
