// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A file uploaded to the engine (`POST /api/files`), stored next to the workspace.
 */
export type FileRef = { id: string, 
/**
 * Sent as the part's filename.
 */
name: string, contentType: string, size: number, };
