// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FindingLevel } from "./FindingLevel";

export type Finding = { level: FindingLevel, message: string, };
