// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FieldKind } from "./FieldKind";
import type { FileRef } from "./FileRef";

/**
 * A multipart field. Reads plain `KeyValue`s too, as text fields.
 */
export type FormField = { key: string, kind: FieldKind, 
/**
 * Template. Text fields only.
 */
value: string, 
/**
 * File fields only. None until a file is chosen.
 */
file: FileRef | null, enabled: boolean, };
