// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CapsInfo } from "./CapsInfo";

/**
 * `GET /api/health`. Public (no session), like the version; the caps aren't secret, and the UI uses
 * them to say what's allowed before the engine has to refuse it.
 */
export type HealthResponse = { ok: boolean, version: string, caps: CapsInfo, };
