// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Collection } from "./Collection";

/**
 * `POST /api/import`. The UI adds `collection` to the workspace.
 */
export type ImportResult = { collection: Collection, 
/**
 * E.g. "OpenAPI 3.0.3".
 */
format: string, 
/**
 * Things that were skipped or guessed, for the user to review.
 */
warnings: Array<string>, };
