// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImportSource } from "./ImportSource";

export type ImportRequest = { source: ImportSource, 
/**
 * Overrides the spec's title as the collection name.
 */
name: string | null, };
