// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ImportSource = { "type": "text", content: string, } | { "type": "url", url: string, };
