// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Role } from "./Role";

export type InviteInfo = { id: string, email: string, role: Role, invitedBy: string | null, createdAtMs: number, expiresAtMs: number, };
