// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InviteInfo } from "./InviteInfo";

export type InviteCreated = { invite: InviteInfo, 
/**
 * The link to join, for the admin to pass on by other means (always given, emailed or not).
 */
link: string, 
/**
 * Whether it was emailed (only when this engine has SMTP set up, and the send worked).
 */
emailed: boolean, };
