// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LatencyConfig = {
  /**
   * An endpoint saved in the workspace.
   */
  endpointId: string;
  /**
   * Overrides the workspace's active environment.
   */
  environment: string | null;
  warmup: number;
  samples: number;
  keepAlive: boolean;
  timeoutMs: number;
  /**
   * Status codes that count as success even though they're 4xx/5xx.
   */
  okStatuses: Array<number>;
};
