// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LoadMode } from "./LoadMode";
import type { MixEntry } from "./MixEntry";
import type { TokenRefreshConfig } from "./TokenRefreshConfig";

export type LoadConfig = { endpointId: string, environment: string | null, mode: LoadMode, durationMs: number, 
/**
 * Linear ramp from ~0 to full concurrency/rate over this long. 0 = no ramp.
 */
rampUpMs: number, timeoutMs: number, keepAlive: boolean, 
/**
 * Open model only: sends beyond this many in flight are dropped (and counted). Defaults to the cap.
 */
maxInFlight: number | null, 
/**
 * Status codes that count as success even though they're 4xx/5xx (e.g. an expected 404).
 */
okStatuses: Array<number>, 
/**
 * Multi-endpoint mix (HANDOFF → v1.x → Multi-endpoint mix): each request goes to one of these,
 * chosen by weight. Empty means just `endpoint_id`. When set it must include `endpoint_id`, and
 * every endpoint must be on the same host, since a run pins one host's address.
 */
mix: Array<MixEntry>, 
/**
 * Keeps a short-lived token fresh during the run (HANDOFF → Open questions 3).
 */
tokenRefresh: TokenRefreshConfig | null, };
