// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BreakpointMode } from "./BreakpointMode";
import type { RateLimitMode } from "./RateLimitMode";
import type { SpikeMode } from "./SpikeMode";

export type LoadMode = { "type": "closed", concurrency: number, } | { "type": "open", rate: number, } | { "type": "breakpoint" } & BreakpointMode | { "type": "spike" } & SpikeMode | { "type": "rateLimit" } & RateLimitMode | { "type": "soak", rate: number, };
