// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Role } from "./Role";

export type MemberInfo = { userId: string, email: string, role: Role, joinedAtMs: number, 
/**
 * The signed-in user.
 */
you: boolean, };
