// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InviteInfo } from "./InviteInfo";
import type { MemberInfo } from "./MemberInfo";

/**
 * `GET /api/workspaces/{id}/members`.
 */
export type MembersResponse = { members: Array<MemberInfo>, 
/**
 * Invites not yet accepted. Only admins see these; empty for everyone else.
 */
invites: Array<InviteInfo>, };
