// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AuthMode } from "./AuthMode";
import type { UserInfo } from "./UserInfo";

/**
 * `GET /api/auth/me`, and what signing in returns.
 */
export type MeResponse = { auth: AuthMode, 
/**
 * Whether new accounts can be created from the UI.
 */
signup: boolean, 
/**
 * The signed-in user; `None` when signed out or when auth is off.
 */
user: UserInfo | null, 
/**
 * The workspace the UI should use (it sends this as `X-Kestrel-Workspace`).
 */
workspaceId: string | null, };
