// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AuthMode } from "./AuthMode";
import type { UserInfo } from "./UserInfo";
import type { WorkspaceInfo } from "./WorkspaceInfo";

/**
 * `GET /api/auth/me`, and what signing in returns.
 */
export type MeResponse = { auth: AuthMode, 
/**
 * Whether new accounts can be created from the UI.
 */
signup: boolean, 
/**
 * Whether this engine can send email (`KESTREL_SMTP_HOST`), so verification and password
 * reset are available.
 */
mail: boolean, 
/**
 * The signed-in user; `None` when signed out or when auth is off.
 */
user: UserInfo | null, 
/**
 * The workspace the UI should use (it sends this as `X-Kestrel-Workspace`): the one it asked
 * for if the user is still a member, else their default.
 */
workspaceId: string | null, 
/**
 * Every workspace the user belongs to, with their role in each. Empty when signed out or off.
 */
workspaces: Array<WorkspaceInfo>, };
