// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MixEntry = { endpointId: string, 
/**
 * Relative share of requests: weights 3 and 1 send three quarters to the first.
 */
weight: number, };
