// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LatencySummary } from "./LatencySummary";
import type { StatusCount } from "./StatusCount";

/**
 * One endpoint's share of a multi-endpoint run.
 */
export type MixStats = { endpointId: string, name: string, weight: number, requests: number, errors: number, latency: LatencySummary | null, statusCounts: Array<StatusCount>, };
