// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Model } from "./Model";

export type ModelFit = { model: Model, 
/**
 * Intercept (ms): the fixed cost, network included.
 */
a: number, 
/**
 * Coefficient on f(n), ≥ 0.
 */
b: number, r2: number, 
/**
 * Lower is better. Differences under ~4 mean "hard to tell apart".
 */
aicc: number, };
