// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `POST /api/auth/password-reset`: email a reset link, if there's an account.
 */
export type PasswordResetRequest = { email: string, };
