// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Finding } from "./Finding";
import type { PayloadPoint } from "./PayloadPoint";

export type PayloadResult = { points: Array<PayloadPoint>, 
/**
 * From a straight line through latency against bytes: what a request costs whatever its size,
 * and the effective throughput for the bytes on top. None when the payload didn't vary enough
 * (or, for the rate, when size made no difference).
 */
fixedMs: number | null, mbPerS: number | null, 
/**
 * The best MB/s at any one size.
 */
peakMbPerS: number | null, findings: Array<Finding>, };
