// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PayloadPoint = { n: number, 
/**
 * Median request plus response body bytes at this size.
 */
bytes: number, medianMs: number, 
/**
 * `bytes` over the median latency.
 */
mbPerS: number, };
