// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LatencySummary } from "./LatencySummary";

/**
 * A request's time split into phases. Measured from when the request was sent, so in an open-model
 * load run it leaves out time spent queued behind the in-flight cap.
 */
export type PhaseSummary = { 
/**
 * Resolving the host, once per run (the address is then pinned). None for an IP in the URL.
 */
dnsMs: number | null, 
/**
 * Requests that opened a new connection, out of `requests`. With keep-alive this is usually
 * just the first few; without it, every request.
 */
newConnections: number, requests: number, 
/**
 * Opening a connection (TCP + TLS), for the requests that opened one.
 */
connect: LatencySummary | null, 
/**
 * From sending (after any connect) until the response headers arrived: the server's work plus
 * a network round trip.
 */
waiting: LatencySummary | null, 
/**
 * Reading the body after the headers arrived.
 */
download: LatencySummary | null, };
