// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `PUT /api/auth/profile`.
 */
export type ProfileRequest = { 
/**
 * Up to 80 characters; empty clears it.
 */
name: string, };
