// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BreakpointStep } from "./BreakpointStep";

export type RateLimitResult = { 
/**
 * `error_pct` is the share of 429s.
 */
steps: Array<BreakpointStep>, 
/**
 * The highest step without 429s (to within 1%).
 */
heldRate: number | null, 
/**
 * The first step with 429s. None if none had them.
 */
limitedAtRate: number | null, 
/**
 * Rate-limit headers (`Retry-After`, `X-RateLimit-*`, `RateLimit-*`) on the first 429.
 */
limitedHeaders: Array<[string, string]>, 
/**
 * The same headers on the first other response: many APIs announce their limits on every
 * response.
 */
okHeaders: Array<[string, string]>, };
