// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RateLimitMode = { startRate: number, stepPercent: number, stepMs: number, maxRate: number, };
