// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a member may do in a workspace. Any number of admins, but always at least one.
 */
export type Role = "admin" | "write" | "read";
