// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FakeConfig } from "./FakeConfig";
import type { LatencyConfig } from "./LatencyConfig";
import type { LoadConfig } from "./LoadConfig";

/**
 * Body of `POST /api/runs`. Tagged by `kind`; real tests are added as variants.
 */
export type RunConfig = { "kind": "fake" } & FakeConfig | { "kind": "latency" } & LatencyConfig | { "kind": "load" } & LoadConfig;
