// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Bucket } from "./Bucket";
import type { FinishedEvent } from "./FinishedEvent";
import type { StartedEvent } from "./StartedEvent";

/**
 * One SSE `data:` payload. The SSE `id:` line carries the event id, not this struct.
 */
export type RunEvent = { "type": "started" } & StartedEvent | { "type": "bucket" } & Bucket | { "type": "resync" } | { "type": "finished" } & FinishedEvent;
