// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Bucket } from "./Bucket";
import type { ComplexityResult } from "./ComplexityResult";
import type { ContractSummary } from "./ContractSummary";
import type { ErrorCounts } from "./ErrorCounts";
import type { HistogramBin } from "./HistogramBin";
import type { LatencySummary } from "./LatencySummary";
import type { RunConfig } from "./RunConfig";
import type { RunStatus } from "./RunStatus";
import type { Sample } from "./Sample";
import type { StatusCount } from "./StatusCount";
import type { TargetInfo } from "./TargetInfo";

export type RunReport = { runId: string, config: RunConfig, status: RunStatus, startedAtMs: number, finishedAtMs: number, totalRequests: number, totalErrors: number, meanRps: number, maxP99Ms: number, 
/**
 * Target host and the IP it was pinned to.
 */
target: TargetInfo | null, 
/**
 * All requests, failures and timeouts included. Headline numbers use this.
 */
latency: LatencySummary | null, 
/**
 * Successful requests only.
 */
latencySuccess: LatencySummary | null, 
/**
 * Time to first byte (response headers), all requests.
 */
ttfb: LatencySummary | null, 
/**
 * Distribution of all requests.
 */
histogram: Array<HistogramBin>, 
/**
 * The very first request of the run (a warm-up if any), reported apart from the rest.
 */
coldMs: number | null, statusCounts: Array<StatusCount>, errorCounts: ErrorCounts, 
/**
 * A few redacted request/response pairs: the first success and the first errors.
 */
samples: Array<Sample>, 
/**
 * Things the reader should know, e.g. "stopped at the duration cap".
 */
notes: Array<string>, 
/**
 * Open model: scheduled sends that were never issued because of the in-flight cap.
 */
dropped: number, 
/**
 * Open model: how late the scheduler issued sends.
 */
generatorLag: LatencySummary | null, 
/**
 * Per-window results, as streamed during the run.
 */
timeline: Array<Bucket>, 
/**
 * Contract checks against the spec, when the endpoint was imported from one.
 */
contract: ContractSummary | null, 
/**
 * Big-O runs only.
 */
complexity: ComplexityResult | null, };
