// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The few report numbers a run list shows.
 */
export type RunResult = { finishedAtMs: number, totalRequests: number, totalErrors: number, meanRps: number, 
/**
 * All requests, as in the report's headline latency.
 */
p50Ms: number | null, p99Ms: number | null, };
