// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RunKind } from "./RunKind";
import type { RunResult } from "./RunResult";
import type { RunStatus } from "./RunStatus";

export type RunSummary = { runId: string, kind: RunKind, status: RunStatus, startedAtMs: number, 
/**
 * The endpoint under test; none for synthetic runs. It may since have been deleted.
 */
endpointId: string | null, 
/**
 * Headline numbers, once the run has finished.
 */
result: RunResult | null, };
