// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RunKind } from "./RunKind";
import type { RunStatus } from "./RunStatus";

export type RunSummary = { runId: string, kind: RunKind, status: RunStatus, startedAtMs: number, };
