// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExtractTarget } from "./ExtractTarget";

/**
 * Outcome of one extract rule.
 */
export type Saved = { name: string, target: ExtractTarget, 
/**
 * Variables only; secrets are write-only. None if the rule failed.
 */
value: string | null, error: string | null, };
