// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `PUT /api/workspace` succeeded.
 */
export type SaveWorkspaceResponse = { revision: number, };
