// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContractCheck } from "./ContractCheck";
import type { ErrorClass } from "./ErrorClass";
import type { Saved } from "./Saved";
import type { SentRequest } from "./SentRequest";

/**
 * `POST /api/send`: the sample, plus what the endpoint's extract rules saved.
 */
export type SendResponse = { saved: Array<Saved>, request: SentRequest, status: number | null, error: string | null, errorClass: ErrorClass | null, ttfbMs: number, totalMs: number, 
/**
 * Opening a new connection (TCP + TLS), part of `ttfb_ms`. None when a pooled one was reused.
 */
connectMs: number | null, responseHeaders: Array<[string, string]>, 
/**
 * UTF-8 (lossy), truncated.
 */
body: string, bodyBytes: number, bodyTruncated: boolean, 
/**
 * Whether this response matches the spec, when the endpoint was imported from one.
 */
contract: ContractCheck | null, };
