// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HttpMethod } from "./HttpMethod";

export type SentRequest = { method: HttpMethod, url: string, headers: Array<[string, string]>, body: string | null, };
