// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One signed-in device or browser, for the Security tab.
 */
export type SessionInfo = { 
/**
 * Opaque; pass it back to revoke the session. (It's derived from the token's hash, which
 * can't be turned back into a token.)
 */
id: string, 
/**
 * The session making this request.
 */
current: boolean, createdAtMs: number, lastSeenAtMs: number, expiresAtMs: number, userAgent: string | null, ip: string | null, };
