// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `DELETE /api/auth/sessions`: how many other sessions were signed out.
 */
export type SessionsEnded = { ended: number, };
