// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `PUT /api/admin/users/{id}/disabled`.
 */
export type SetDisabledRequest = { disabled: boolean, };
