// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Role } from "./Role";

export type SetRoleRequest = { 
/**
 * `admin`, `write` or `read`.
 */
role: Role, };
