// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `PUT /api/secrets`. `value: null` deletes the secret.
 */
export type SetSecretRequest = { environment: string; key: string; value: string | null };
