// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Finding } from "./Finding";
import type { SoakWindow } from "./SoakWindow";

/**
 * Soak runs: the run in windows, and what drifted.
 */
export type SoakResult = { 
/**
 * Window width, sized from the run's length (1 s to 60 s).
 */
windowMs: number, windows: Array<SoakWindow>, findings: Array<Finding>, };
