// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SoakWindow = { 
/**
 * Window start, from the run start (by scheduled time).
 */
tMs: number, requests: number, 
/**
 * Failed or dropped, of those scheduled.
 */
errorPct: number, 
/**
 * 401 or 403, of those scheduled.
 */
authFailurePct: number, p50Ms: number, p99Ms: number, };
