// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SpikePhase } from "./SpikePhase";

export type SpikeResult = { 
/**
 * The baseline before the burst, without its first (warm-up) second.
 */
baseline: SpikePhase | null, spike: SpikePhase | null, after: SpikePhase | null, 
/**
 * How long after the burst ended the target was back to normal (one-second windows with p99
 * within 1.5× the baseline's and no more than one point more errors) and stayed there. None if
 * it hadn't recovered by the end of the run.
 */
recoveryMs: number | null, };
