// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Numbers for one part of a spike run.
 */
export type SpikePhase = { requests: number, 
/**
 * Successful responses per second.
 */
achievedRps: number, 
/**
 * Failures plus drops, as a percentage of everything scheduled.
 */
errorPct: number, p50Ms: number, p99Ms: number, };
