// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SpikeMode = { baseRate: number, spikeRate: number, 
/**
 * Baseline before the burst. Its first second is warm-up and isn't part of "normal".
 */
beforeMs: number, spikeMs: number, 
/**
 * Baseline after the burst: the window recovery is measured in.
 */
afterMs: number, };
