// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RunConfig } from "./RunConfig";

export type StartedEvent = { runId: string, config: RunConfig, startedAtMs: number, };
