// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Finding } from "./Finding";
import type { LatencySummary } from "./LatencySummary";

/**
 * Timeout runs: whether the server hangs or fails fast, and whether requests the client gave up on
 * slowed the ones after them.
 */
export type TimeoutResult = { 
/**
 * The burst's client timeout, as used (picked from the probes when the config said 0).
 */
tightMs: number, 
/**
 * Probes before the burst.
 */
before: LatencySummary | null, 
/**
 * Probes after the burst.
 */
after: LatencySummary | null, 
/**
 * Burst requests sent, and how many of them were answered within `tight_ms` anyway.
 */
abandoned: number, answeredInTime: number, 
/**
 * Probes that ran into the generous timeout: the server never answered.
 */
hung: number, 
/**
 * Probes that failed (5xx or no response) well inside the timeout.
 */
fastFailures: number, 
/**
 * From the end of the burst until probes were back to normal for good. None if they never were
 * (or never slowed).
 */
recoveredAfterMs: number | null, findings: Array<Finding>, };
