// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TimeoutConfig = { endpointId: string, environment: string | null, 
/**
 * Sequential probes before the burst, and again after it.
 */
samples: number, 
/**
 * Requests in the burst, each given up on after `tight_ms`.
 */
abandoned: number, 
/**
 * Burst requests in flight at once.
 */
concurrency: number, 
/**
 * The burst's client timeout. 0 picks a quarter of the probes' median, so most are abandoned.
 */
tightMs: number, 
/**
 * The probes' timeout: generous, so a request that reaches it means the server hung.
 */
timeoutMs: number, };
