// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TokenRefreshConfig = { 
/**
 * An endpoint whose On Response rules pick the token out of its response.
 */
endpointId: string, 
/**
 * How often to fetch a new token. It's also fetched at the start, and early on 401s.
 */
everyMs: number, };
