// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Endpoint } from "./Endpoint";

/**
 * `POST /api/render` and `POST /api/send`. Takes the endpoint inline so unsaved drafts can be tried.
 */
export type TryRequest = {
  endpoint: Endpoint;
  environment: string | null;
  timeoutMs: number | null;
};
