// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What signing in returns instead of a session when the account has two-factor on.
 */
export type TwoFactorChallenge = { 
/**
 * Send back with the code to `POST /api/auth/login/2fa`. Works for 5 minutes and 5 tries.
 */
twoFactorChallenge: string, };
