// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `POST /api/auth/2fa/enable`: a code from the app, proving it was set up.
 */
export type TwoFactorCode = { code: string, };
