// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The new secret, to add to an authenticator app. Not active until confirmed with a code.
 */
export type TwoFactorSetup = { 
/**
 * Base32, for typing into the app by hand.
 */
secret: string, 
/**
 * `otpauth://…`, for a QR code.
 */
otpauthUrl: string, };
