// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `POST /api/auth/login/2fa`.
 */
export type TwoFactorLogin = { challenge: string, 
/**
 * A 6-digit code from the app, or a recovery code.
 */
code: string, };
