// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `POST /api/auth/2fa/disable` and `/2fa/recovery-codes`: the password and a current code (or a
 * recovery code), so a stolen session alone can't do either.
 */
export type TwoFactorConfirm = { password: string, code: string, };
