// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `GET /api/auth/2fa`.
 */
export type TwoFactorStatus = { enabled: boolean, recoveryCodesLeft: number, };
