// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `POST /api/auth/2fa/setup`: confirm the password before a new secret is made.
 */
export type TwoFactorSetupRequest = { password: string, };
