// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UserInfo = { id: string, email: string, 
/**
 * Whether the user has followed a verification (or password reset) link.
 */
emailVerified: boolean, };
