// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Collection } from "./Collection";
import type { Environment } from "./Environment";

export type Workspace = {
  collections: Array<Collection>;
  environments: Array<Environment>;
  activeEnvironment: string | null;
  /**
   * The collection shown expanded in the sidebar.
   */
  activeCollection: string | null;
};
