// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `POST /api/workspaces` (create) and `PATCH /api/workspaces/{id}` (rename).
 */
export type WorkspaceNameRequest = { name: string, };
