// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Endpoint } from "./Endpoint";
import type { Environment } from "./Environment";

export type Workspace = { endpoints: Array<Endpoint>, environments: Array<Environment>, activeEnvironment: string | null, };
