// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkspaceResponse } from "./WorkspaceResponse";

/**
 * `PUT /api/workspace` was refused with 409: someone saved since `baseRevision`. Nothing was
 * written. `current` is what's there now, to merge the edits into and save again.
 */
export type WorkspaceConflict = { error: string, 
/**
 * Always `"workspaceConflict"`.
 */
code: string, current: WorkspaceResponse, };
