// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Workspace } from "./Workspace";

/**
 * `GET /api/workspace`. Secrets are write-only, so only their names are returned.
 */
export type WorkspaceResponse = { workspace: Workspace, 
/**
 * Environment name → names of the secrets set for it.
 */
secretKeys: { [key in string]: Array<string> }, };
