// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Role } from "./Role";

/**
 * One of the signed-in user's workspaces.
 */
export type WorkspaceInfo = { id: string, 
/**
 * Its name, or "<admin>'s workspace" for one that was never named.
 */
name: string, 
/**
 * The signed-in user's role in it.
 */
role: Role, members: number, 
/**
 * Its admins' emails, longest-standing first.
 */
adminEmails: Array<string>, };
