// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Workspace } from "./Workspace";

/**
 * `GET /api/workspace`. Secrets are write-only, so only their names are returned.
 */
export type WorkspaceResponse = { workspace: Workspace, 
/**
 * Environment name → names of the secrets set for it.
 */
secretKeys: { [key in string]: Array<string> }, 
/**
 * Bumped by every save. Send it back as `baseRevision` when saving, so a save made without
 * seeing someone else's changes is refused instead of overwriting them.
 */
revision: number, };
